version: '3.3'

services:
    database:
        build:
            context: ./docker/mysql
            dockerfile: Dockerfile
        container_name: url-shorneter_database
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root12345
        ports:
            - '3306:3306'
